- src/components/QrcodeReader.vue
Changelog:
* Added playsInline and play() to the video stream so it works with the WebRTC Safari implementation.
Notes:
* The camera will only work inside Safari. If you add the webapp to your homescreen the camera will not work and you won't get any error, the same is true for chrome, firefox or a webview inside an app since there is no WebRTC in its WebKit implementation yet.
* I was able to get it running on an android tablet with Chrome running on a KitKat 4.4 after adding the lines. But sometimes the browser just ignores and never prompt to allow the camera again or throw any error, only a reboot it was working again (maybe google's implementation of WebRTC is still buggy?). I wasn't able to test on an Android phone yet.
> Fixed black screen on iOS 11/Safari 11

- src/components/QrcodeReader.vue
- src/misc/camera.js
Hey, thanks for the great component! Very happy with it so far. Except when using low power mode in ios.
It seems that video elements aren't allowed to play without user interaction to enable it. With these attributes the stream is set to autoplay, be muted and also to display inline just to make certain that it won't accidentally pop up full screen.
Reference:
https://webkit.org/blog/6784/new-video-policies-for-ios/
I can't say for certain what side effects this will have because I have only tested it with my devices. But for Firefox and safari on Mac OS Mojave and iPhone 8 running ios 12 the behavior is unchanged. Except of course that there is a working scan and video stream when using the latter on low power mode.
> Add video attributes to always allow iOS playback

- README.md
- src/components/QrcodeCapture.vue
- src/components/QrcodeStream.vue
- src/index.js
- src/misc/camera.js
- src/misc/errors.js
Introducing a dedicated component for classic file upload/media capture. 
Import independently from main component:
```js
import { QrcodeReader, QrcodeCapture } from 'vue-qrcode-reader'
```
The component emits `decode` and `detect` exactly like the main component:
```html
<qrcode-capture @decode="..." @detect="..." />
```
The component renders to a simple `input` element:
```html
<input
type="file"
name="image"
accept="image/*"
capture="environment"
multiple>
```
> Split qrcode-reader in 3 different components

- src/misc/camera.js
StreamApiNotSupportedError is not getting thrown on Chrome in iOS because the conditional logic for the variable STREAM_API_SUPPORTED is _undefined_ and not _false_. This changes the logic to check for anything _falsey_ instead of _false_.
> Fix for StreamApiNotSupportedError exception

- demo.html
- src/components/QrcodeStream.vue
- src/misc/camera.js
Modern phones often have multipe front/rear cameras.
Sometimes special purpose cameras like the wide-angle camera are picked
by default. Those are not optimal for scanning QR codes but standard
media constraints don't allow us to specify which camera we want exactly.
However, we can obtain a list of all video input devices with
navigator.mediaDevices.enumerateDevices()
Picking the first entry as the default front camera and the last entry
as the default rear camera seems to be a valid heuristic.
Issue: #179
> fix: narrow down camera selection

- src/misc/camera.js
There is a bug with MediaStream in Chrome on Android 11 that causes the page to freeze when a MediaStream is paused or stopped. This PR is a workaround, first found by @BelkinVadim on this thread: https://github.com/twilio/twilio-video-app-react/issues/355#issuecomment-780368725.
Closes #228
> fix: application freezes when stream is paused or stopped

- src/worker/jsqr.js
Fixes #207  on recent iOS versions where the QR Scanner stops working after about 30 seconds. This is due to an uncaught RangeError exception in jsQR.
> Fix iOS RangeError bug

- src/misc/scanner.js
DropImageDecodeError was removed in https://github.com/gruhn/vue-qrcode-reader/commit/dea620ec69f0644c3c7282aff08686c8f639edbb
> Remove unused obsolete import

- docs/api/QrcodeCapture.md
- package-lock.json
- src/components/QrcodeCapture.vue
- src/components/QrcodeDropZone.vue
- src/components/QrcodeStream.vue
HTML is not considered as a preprocessor language by vite currently: https://github.com/vitejs/vite/issues/10033
> fix(vue-3): remove default template language

- src/misc/camera.js
The iPhone Desk View Cameras have to be added to the blacklist.
They have a different name in every language; This commit adds "de", "fr" and "it".
More info: https://support.apple.com/en-us/HT213244
> fix(camera): Desk View Cameras added to blacklist (de, fr, it)

- src/misc/camera.js
This PR adds 4 new cameras (dual+triple, each in DE+EN) to the blacklist. It seems that those were introduced with the latest release of iOS 16.4.
I also added line breaks to the `deviceBlackList` to make future updates easier to diff.
> fix(camera): add dual/triple rear cameras to blacklist (de+en)

- src/misc/camera.js
Fix IOS 16 bug - incorrect camera by default
> fix(camera): back ultra wide camera added to blacklist (en)

- package.json
Update dependency of barcode-detector to a minimum version which includes also decoding inverted QR codes. 
Related #238
> fix: attempt to decode inverted QR codes

- README.md
- package.json
- pnpm-lock.yaml
- src/index.ts
- src/misc/scanner.ts
The BarcodeDetector polyfill fetches a WASM file at runtime from a CDN. That's a problem for offline applications or applications that run in a network with strict CSP policy. As a workaround the polyfill exports a function to configure the WASM file URL. So we re-export the function here.
Also, by default the BarcodeDetector polyfill installs itself by setting `globalThis.BarcodeDetector` but only if there is no native support. This is likely not SSR compatible. Also, native support `BarcodeDetector` is inconsistent. For example, Chrome on MacOS does support `BarcodeDetector` but does not support `Blob` inputs, violating the specification. To have a more consistent support we simply always use the polyfill on all platforms. That likely comes as at a performance cost in raw scanning speed …
> feat: re-export setZXingModuleOverrides

- package.json
- pnpm-lock.yaml
- src/components/QrcodeStream.vue
- vite.config.ts
- Update `@sec-ant/barcode-detector` to v1.2.2
- Most error/exception messages are in consistent with those from the Chromium native implementation.
- A more detailed [`.wasm` fetch error message](https://github.com/Sec-ant/barcode-detector/blob/aacece7c21a3439cc6407c81c130d85c8b9e68de/src/BarcodeDetector.ts#L111) so ppl at least will know what to search when it happens.
- Removes the lookbehind regex mentioned in #363 .
- Set `optional-catch-binding` flag to `false` to let esbuild transform this syntax. This should fix #359 . Although the syntax should be already widely supported from es2019 (the default target of Vite is es2020), the transformation overhead is trivial. I can revert this if this is not intended.
> fix: compatibility issues

- shell.nix
- src/components/QrcodeStream.vue
- src/misc/scanner.ts
For some users the external style.css is not automatically imported. Now inline all CSS to avoid external CSS files in general.
See #360
> fix(QrcodeStream): styling sometimes missing

- docs/api/QrcodeStream.md
In "did you requested the front camera although there is none?" the past tense is already inflected in the auxiliary verb "did", so the infinitive (base) form of the verb should be used here. 
> docs(QrcodeStream.md): Fixed typo

- .eslintrc.cjs
- package.json
- pnpm-lock.yaml
- src/components/QrcodeCapture.vue
- src/components/QrcodeDropZone.vue
- src/components/QrcodeStream.vue
- src/index.ts
- src/misc/scanner.ts
- vite.config.ts
- `@sec-ant/barcode-detector` package name changed to `barcode-detector`
- `barcode-detector@2.0.1` supports iOS/Safari 13.0
This was requested by https://github.com/Sec-ant/barcode-detector/issues/11 .
The new version also attempts to address #368 without introducing a polyfill for `createImageBitmap`.
> chore: switch to barcode-detector@2.0.1

- README.md
Fix #367 
Personally I think `index.umd.js` or `/umd/index.js` may be better options, as some cloud services fail to set the proper content-type for `.cjs` extensions ([ref](https://stackoverflow.com/a/76774057/4668057)). And `vue-qrcode-reader` occurs twice in the link, seems a little lengthy.
UPKG will mark `.cjs` with the content type of `text/plain`:
<details>
</details>
jsDelivr will mark it with `application/node`:
<details>
</details>
> docs(README): fix umd script link

- docs/.vitepress/components/demos/Upload.vue
When set to `false`, it still evokes the camera. (An invalid value of `false` will be falls back to the implementation-specific default facing mode.)
Removing the `capture` attribute by setting it to `null` forces the file dialog correctly.
> docs(QrcodeCapture): Valid values for the force file dialog

- package.json
- pnpm-lock.yaml
use exact version rather than semver range to prevent users from unexpectedly hosting a wrong `.wasm` file from `node_modules` see: https://github.com/gruhn/vue-qrcode-reader/issues/354#issuecomment-1722257982
> fix(wasm): pin `barcode-detector`

- .eslintrc.cjs
- docs/.vitepress/components/demos/Torch.vue
Add camera picker to Torch demo, so users can select a different camera, if the default choice does not support torch.
See: #380
> docs: camera picker for torch demo

- docs/demos/Simple.md
- docs/public/simple-demo.html
- package.json
- src/index.ts
(1) Remove global plugin installation idiom from `src/index.ts` since
`Vue.use` was removed in Vue 3 and causes an error when actually
executed. See:
https://v3-migration.vuejs.org/breaking-changes/global-api.html#a-note-for-plugin-authors
(2) Add an additional build artifact `vue-qrcode-reader.umd.js` that
is just a copy of `vue-qrcoder-reader.umd.cjs`. Doing a `script`-
tag import of `cjs` files, doesn't work  if the server doesn't also
set the `Content-Type` correctly (as pointed out by @Sec-ant),
which is the case with some Unpkg for example. So it seems weird
that Vite uses that as the default file type for UMD artifacts.
The purpose of UMD is to be both compatible with CommonJS and
simple `script` imports. Let's keep both files for backwards-
compatibility for now.
(3) Instead of …
> fix: "Simple" workflow

- src/components/QrcodeStream.vue
- src/misc/camera.ts
Implement a task queue to keep camera start and stop tasks in order and mitigate potential race conditions.
Users will notice some delay when they open and close the camera frequently (e.g. switching cameras quickly, turning on and off the torch quickly, etc.) because each start and stop action is saved in the task queue and dequeues in order, with no abortion.
Abortion can be added if this is a matter of concern.
> refactor(camera.ts): task queue

- package.json
- pnpm-lock.yaml
There's a bug in barcode-detector@2.1.0 that prevents loading `.wasm` from a custom url, @2.1.1 fixed it.
> fix(wasm): custom `.wasm` loading issue

- src/components/QrcodeStream.vue
Scanner does not work anymore after when `deviceId` via `constraints` is updated and no other props are changed. This is because:
==> both `cameraActive.value` and `cameraSettings.shouldStream` stay `true`
==> then `shouldScan` also does not change
==> therefore the watcher on `shouldScan` is not triggered
==> and finally we don't start a new scanning process
To prevent that, we now explicitly set `cameraActive` to `false` right before requesting a new camera. That is not just a hack but also makes semantically sense, because the camera is briefly inactive right before requesting a new camera.
See: #416
> fix: scanner breaks after constraint update

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/main.yml
- .github/workflows/preview.yml
- CONTRIBUTING.md
- README.md
- docs/.vitepress/config.ts
- package.json
Migrate away from Netlify after reading this story:
https://www.reddit.com/r/webdev/comments/1b14bty/netlify_just_sent_me_a_104k_bill_for_a_simple/
> ci: migrate docs to back to GitHub pages

- package.json
- src/components/QrcodeCapture.vue
- src/components/QrcodeDropZone.vue
- src/components/QrcodeStream.vue
- src/misc/scanner.js
vue-qrcode-reader^3.x version Support barcode formats other than QR codes
1. Upgrade barcode detector dependency from 1.0.3 to 2.2.2 to provide support for barcode formats other than QR codes
> feat：support formats

- docs/.vitepress/components/demos/FullDemo.vue
- docs/.vitepress/config.ts
- src/misc/camera.ts
- src/misc/scanner.ts
When listing available cameras with `enumerateDevices` the `label` field is an empty string in some browsers. In that case, the dropdown to select a camera on the "full demo" is invisible because all selectable options are empty strings. Fixing that by also including the device ID (not just the label) so some text is always rendered.
Also added logging statements for all kinds of state transitions.
> fix(FullDemo): hidden device ID dropdown

- .gitignore
- src/misc/scanner.ts
- src/misc/shimGetUserMedia.ts
- src/misc/util.ts
* feat: only install polyfill if there is no native support
* Modified gitignore to ignore vitepress cache and dist
> feat: only install polyfill if there is no native support (#447)

- docs/api/QrcodeStream.md
- src/components/QrcodeStream.vue
- src/misc/scanner.ts
Previously we always used the native `BarocdeDetector` implementation if available. However, the native API might be available but does not support the barcode formats requested by the user. For example, `"qr_code"` might be supported but the user wants to scan `["qr_code", "aztec"]`. In these cases, we now also fallback to the polyfill implementation.
Closes #450
> fix: native `BarocdeDetector` doesn't support requested formats

- .github/workflows/main.yml
- docs/api/QrcodeStream.md
- package.json
- pnpm-lock.yaml
- src/components/QrcodeCapture.vue
- src/components/QrcodeDropZone.vue
- src/components/QrcodeStream.vue
- src/index.ts
- src/misc/errors.ts
- tsconfig.app.json
See: #460
@true-vue I tried to implement your suggestion. What do you think?
> feat: export component prop types

- src/misc/scanner.ts
- src/misc/util.ts
The native BarcodeDetector implementation on desktop Mac seems to support PDF417 codes but when scanning (always?) returns an empty string. Thus, now falling back to polyfill under these conditions.
See: #459
> fix: PDF471 codes on desktop Mac

- src/components/QrcodeStream.vue
This fixes a small issue with the exported type for `QrcodeStream` - that originated in cc200c46fcce1ccbc1e9176fcf303ad56859d025 (My app works and build with v5.6.0, but does not build with v5.7.0).  When building my app, I got the following typescript error.
```
src/components/CodeScanner.vue:138:8 - error TS2322: Type '{ deviceId?: string | undefined; facingMode?: string | undefined; }' is not assignable to type '{ facingMode: string; }'.
Types of property 'facingMode' are incompatible.
Type 'string | undefined' is not assignable to type 'string'.
Type 'undefined' is not assignable to type 'string'.
138       :constraints="selectedConstraints"
~~~~~~~~~~~
node_modules/vue-qrcode-reader/dist/components/QrcodeStream.vue.d.ts:66:5
66     constraints: {
~~~~~~~~~~~
The expected type comes …
```
> Fix type of constraints in QrcodeStream
