gruhn/vue-qrcode-reader

- src/components/QrcodeReader.vue
Had to add a setTimeout so that the same qr-image would not be scanned from the frozen video stream. 
Have a look-see if it's something you'd be willing to use
> added reset content in paused watch

- src/index.js
Use case: Scan a custom image from anywhere.
> export helper function so user can use.

- src/components/QrcodeReader.vue
Using the `paused` prop the camera stream can be frozen and `decode`/`detect` events are suppressed. The camera is still actively streaming in the background though. Apparent from the notification feed on Android or the red dot next to the tab-close-icon on Desktop Chrome.
This PR allows `paused` behavior utilizing the `camera` prop but without the camera streaming in the background as proposed in #24.
> Allow pausing with non-active camera

- src/components/QrcodeDropZone.vue
> Create `dragover` event in QrcodeDropZone

- src/components/QrcodeStream.vue
Had some issues with coordinates not matching up, traced it down to a reference to offsetWidth where it should be offsetHeight.
> Fixed reference to offsetHeight

- docs/.vuepress/components/demos/DecodeAll.vue
> docs: Update demos/DecodeAll.vue

- package.json
Otherwise the types aren't found for this project as dependency.
> feat(ts): specify types in package

- .github/ISSUE_TEMPLATE/wrong_camera.md
- README.md
- docs/.vuepress/components/demos/Upload.vue
- docs/.vuepress/public/select-camera-demo.html
- docs/demos/Upload.md
- src/components/QrcodeStream.vue
- src/misc/camera.js
- src/misc/scanner.js
Just to have the newest features available for vue3 too :hugs:
> feat: merge master into vue3-compatibility

- src/misc/camera.js
Fix IOS 16 bug - incorrect camera by default
> fix(camera): Desk View Camera was added into blacklist

- src/misc/camera.js
same commit from master just on vue3 branch
nice to have this one with new vue3 tag and ready on npm
> vue3 - fix(camera): Desk View Camera was added into blacklist

- src/misc/camera.js
add czech iphone camera names to deviceBlackList
https://github.com/gruhn/vue-qrcode-reader/issues/322
https://github.com/gruhn/vue-qrcode-reader/pull/326
> fix(camera): czech iphone camera to blackList

- docs/.vitepress/components/demos/CustomTrackingWithFormats.vue
- docs/.vitepress/config.ts
- docs/api/QrcodeCapture.md
- docs/api/QrcodeDropZone.md
- docs/api/QrcodeStream.md
- docs/demos/CustomTrackingWithFormats.md
- src/components/QrcodeCapture.vue
- src/components/QrcodeDropZone.vue
- src/components/QrcodeStream.vue
- src/misc/scanner.ts
> feat: add formats prop

- src/misc/scanner.ts
> docs(scanner): explain scanning delay better

- src/misc/camera.ts
`loadeddata` in iOS WeChat browser won't get fired unless `videoEl.play()` is explicitly triggered.
Fixes #375 
This fix works on my iPhone and I didn't notice any regression on other devices, but we better do some more tests till we release it.
@bububear Check the Netlify deploy preview link below 👇 to see if this works on your device.
> fix(camera): support iOS WeChat browser

- package.json
- pnpm-lock.yaml
- src/misc/camera.ts
- src/types/global.d.ts
This PR is targeting branch at #383 not master.
* Augment types to avoid using `@ts-ignore`.
* Fix torch cannot be turned off by user, or when exits, see #380 .
> fix(torch): cannot be turned off

- package.json
- pnpm-lock.yaml
- src/components/QrcodeStream.vue
- src/misc/camera.ts
- src/types/global.d.ts
> fix: Turn off torch on exit

- .prettierrc.json
- .vscode/settings.json
- docs/.vitepress/components/demos/Torch.vue
This PR fixed the camera flash problem mentioned in https://github.com/gruhn/vue-qrcode-reader/pull/387#issuecomment-1752046052
Code formatting is put in a separate commit and is only my personal preference, it can be dropped if is not intended. 😉
> Fix torch demo

- README.md
Hi, thanks for the reply on my issue. I took the freedom to fix it. If you like, feel free to use it 😄
> docs: fix wrong unpkg link

- package.json
> fix: remove references to nonexistent CJS

- .github/workflows/stale.yml
> ci: dont-mark-stale issue label

- docs/.vitepress/components/demos/DragDrop.vue
- src/components/QrcodeDropZone.vue
> fix(QrcodeDropZone): `formats` prop is not passed along

- package-lock.json
- src/components/QrcodeCapture.vue
- src/components/QrcodeDropZone.vue
- src/components/QrcodeStream.vue
- src/misc/errors.ts
I have made some improvements in emits and props (track) typing. 
Here is scope of changes:
- Detailed types added for events/emits: detect, camera-on, camera-off, error
- track property detailed type added
- Additional type AdjustedCode defined for QrcodeStream.vue
- Comments for props and emits added
One thing to note is `error` argument typing for `error` event. I can add more precise type but need additional info of it's shape - I have left the comment inside the code.
> Types improvements
